Header header


string ROAD_LINE_TOPIC = "roadline_post_processing"
string TRAFFIC_LIGHT_TOPIC = "traffic_light_detection"
string TRAFFIC_SIGN_TOPIC = "traffic_sign_detection"
string LIDAR_DETECTION_TOPIC = "object_detection"
string OBSTACLE_TOPIC = "obstacle_detection"

# Internal Topics
string JSK_LIDAR_BOXES_TOPIC = "jsk_bboxes"
string MERGED_LIDAR_TOPIC = "lidar_merged_visualized"
string OBSTACLE_DEBUG_TOPIC = "obstacle_detection_visualizer"
string ROAD_LINE_DEBUG_TOPIC = "roadline_detection_visualizer"
string ROAD_LINE_MASK_DEBUG_TOPIC = "raw_mask_roadline_detection_visualizer"
string TRAFFIC_LIGHT_DEBUG_TOPIC = "traffic_light_detection_visualizer"
string TRAFFIC_SIGN_DEBUG_TOPIC = "traffic_sign_detection_visualizer"
string ROAD_LINE_MASK_TOPIC = "roadline_detections"
string TRAFFIC_LIGHT_INTERNAL_TOPIC = "traffic_light_internal"
