Header header

geometry_msgs/Pose[] ref_pose_list

float64 cmd_accel
float64 cmd_steer

float64 err_x
float64 err_y
float64 err_yaw
float64 err_vel
float64 err_lat

geometry_msgs/Pose[] act_pose_list

float64 act_lon_vel
float64 act_lat_vel
float64 act_fwd_vel

float64 act_lon_accel
float64 act_lat_accel
float64 act_fwd_accel

float64 act_lon_jerk
float64 act_lat_jerk
float64 act_fwd_jerk

float64 react_time